### PR TITLE
Fix `-p` when tracee is using vfork/exec

### PR DESCRIPTION
**Pull request by Keno**
Since the address space is shared after vfork (and thus not cloned),
we would stop immediately instead of only after the exec. Fix that
by keeping track of the exec in the task.

### CODE REVIEW

**Comment by rocallahan** [comment]
So this exec check will only let you attach to the thread-group leader, right? Because other threads in the same group haven't execed. I think this matters if you pass -p along with -g.

I think we actually need to track exec state on the thread-group.

**Comment by Keno** [comment]
Hmm, yeah that's a fair point.

**Comment by Keno** [comment]
Ok, updated to keep track of this in the task group instead.

**Comment by rocallahan** [comment]
The test fails on my system with `Invalid option -p`. I also get `Targeting recorded pid ...` so the pid wasn't found...

**Comment by rocallahan** [comment]
And record.out contains `FAILED: errno=2 (No such file or directory)`... I think this is because `exec_stub` does not exist anymore, it's called `rr_exec_stub` now. I'll fix...

**Comment by rocallahan** [comment]
Merged. Thanks!!!

**Pull request closed without merging**
