### PR TITLE
adding name_to_handle_at and open_by_handle_at implementations

### PR DESCRIPTION
**Pull request by snf**

### CODE REVIEW

**Comment by rocallahan** [comment]
Thanks!

A test for this would be good.

**Comment by snf** [comment]
I was looking at this again today. The patch made Chrome work again. but I was wondering if there happens anything if the memory to track is bigger than the memory available.
In this patch I set the size to register as `sizeof(struct file_handle) + MAX_HANDLE_SZ` when it can be less but it involves reading memory which might add more overhead.
What do you think?, should I change the patch so it respects the "good" size or it's ok to leave it as the max possible one?
Also, I'm creating some tests.

**Comment by rocallahan** [comment]
`MAX_HANDLE_SZ` is only 128 so I don't think it matters much. I would accept a patch to use the optimal size but I don't mind leaving things the way they are.

**Comment by rocallahan** [comment]
If Chrome uses these a lot, then it might be worth adding syscall-buffering support for these syscalls to `preload.c` to reduce overhead.

**Comment by snf** [comment]
Ok, let's leave it like it is, I prefer the simpler code. And it's only used once by Chrome inside some dbus call so I wouldn't worry about it.

**Pull request merged**
