### PR TITLE
Implement {set,get}_mempolicy support

### PR DESCRIPTION
**Pull request by danobi**

### CODE REVIEW

**Comment by khuey** [comment]
Looks good to me.  Thanks!

**Comment by rocallahan** [comment]
Seems to me that `get_mempolicy` sets its `node` and `nodemask` out-parameters but this patch doesn't account for that, nor is that tested.

**Comment by danobi** [comment]
Please correct me if I'm wrong, but I was under the impression that for emulated (ignored?) syscalls, all we need is a smoke test. Because otherwise, wouldn't we just be testing the validitiy of the kernel API?

**Comment by rocallahan** [comment]
We need to test that system calls like `get_mempolicy` that modify memory actually are modifying memory and that those modifications are being recorded by rr. We need to test that in case there are modifications *not* being recorded by rr, which there are in this case!

**Comment by danobi** [comment]
I think I see what you mean. I will file another patch tomorrow.

**Pull request merged**
