### PR TITLE
Split up mmaps that extend past the end of a file

### PR DESCRIPTION
**Pull request by pipcet**
The old code would fail to coalesce mappings in some cases
(https://github.com/mozilla/rr/commit/8f5a8b5ed63d2389da81865c6f3c0931abb332f0#r30518535).

It would be really nice to have a test for this that fails with the old code (on non-Debian systems).

### CODE REVIEW

**Comment by pipcet** [comment]
Hmm. I must have made a silly mistake during testing, or maybe something changed under me: I'm now seeing test failures unless I remove the code that maps the second part of the mapping, and this appears to be what the code in `record_syscall.cc` does.

**Comment by rocallahan** [comment]
Alright, I'll back this out.

**Comment by rocallahan** [comment]
Done.

**Comment by pipcet** [comment]
Thanks! The commit in #2255 that tries to get this right should be independent of the other two commits. It appears to work, but I'm still confused about where I went wrong with this patch. Maybe I just forgot to recompile between tests...

**Pull request merged**
