### PR TITLE
WIP/RFC: --nested=separate for multi-threaded recording of subtrees

### PR DESCRIPTION
**Pull request by Keno**
A common situation for us is that somewhere along the line in an
rr recording, we spawn a separate process that does a whole bunch
of work, but doesn't share any shared memory with the parent process,
nor does particularly much communication. In an ideal world of course,
rr would detect this kind of situation and record the two tasks in
parallel into the same recording. That seems like a very difficult
task, so this attempts to do the next best thing by letting the user
request this behavior manually.

In particular, any nested rr recording started with
`rr record --nested=separate` will get its own RecordSession, along
with its own recorder thread (and trace compressor threads to its
own thread). Implementation wise, this recorder thread is a thread
of the original rr process (in the sense that it shares its memory
space), but is placed in its own thread group. As a result, its
wait and ptrace state is entirely separate and the two recorders
act essentially as though they are entirely separate processes
(that just happen to share an address space).

This way, I'm hoping to keep this minimally invasive, as each
session is essentially and independent rr process.

Current status: Functional, but a few things remain to be done:
1) The CPU assignment needs to be reset, otherwise there is very
little point to this.
2) Some minor cleanup still.
3) Tests
I'm hoping to get some feedback on the general approach in the
meantime.

### CODE REVIEW

**Comment by rocallahan** [comment]
> Implementation wise, this recorder thread is a thread
of the original rr process (in the sense that it shares its memory
space), but is placed in its own thread group.

I haven't looked at the code yet, but why did you use this unusual setup instead of making the recorder a separate rr process?

**Comment by Keno** [comment]
> I haven't looked at the code yet, but why did you use this unusual setup instead of making the recorder a separate rr process?

So, originally I had thought the easiest way to do this would be just to stop recording entirely, but that turned out to be complicated, because we can't remove the seccomp filter. I have a patch in to the kernel to see what we can do about that, but that's not gonna happen anytime soon.

The next question is why not a separate project forked off from the original rr process.
That didn't work with my original design, but would probably be feasible now. The main
reason I'm sharing the address space is that:
1) Eventually I would like this to just be a regular thread
2) If we don't share the address space and fd table, ideally we'd want to clean up all the file descriptors and memory that's now duplicated. That seemed like a bit of a pain, esp since we don't know what states any other thread may have been in when it forked.

This seems to work fairly well, but if you would like it to be a regular forked process, I think that's probably manageable.

**Comment by rocallahan** [comment]
> Eventually I would like this to just be a regular thread

Because it's more efficient or for some other reason?

> If we don't share the address space and fd table, ideally we'd want to clean up all the file descriptors and memory that's now duplicated. That seemed like a bit of a pain, esp since we don't know what states any other thread may have been in when it forked.

Could we exec? Does ptrace control not survive exec?

**Comment by Keno** [comment]
> Could we exec? Does ptrace control not survive exec?

Yes, we can exec fine, but I want to keep the `Task` alive across the separation, since we need to keep a bunch of its state. We could certainly serialize that, but it seems like a bit of a pain.

**Comment by rocallahan** [comment]
How much state?

**Comment by Keno** [comment]
With the current design whatever is in `Task`/`AddressSpace`/`ThreadGroup`, etc. If we change it around slightly, we could probably spawn off the child recorder earlier in the exec process and only keep state that's preserved across the exec and some file descriptors - at least the memfd and the tracee socket fd. I do worry that doing that would make things quite a bit more complicated though, since we'd have to entry points to all the post-exec processing.

**Comment by Keno** [comment]
> Because it's more efficient or for some other reason?

In an ideal world, I'd like everything to record into the same trace, just with multiple threads servicing the tracee events. At the moment, we'll have to stitch it back together in post-processing if we want to track RPCs across recorded processes, which is fine to do (we have to do it anyway for processes on remote machines), but a bit annoying. It'd probably also be more efficient to share the compressor threads, but I have no numbers on that.

**Comment by rocallahan** [comment]
> At the moment, we'll have to stitch it back together in post-processing if we want to track RPCs across recorded processes, which is fine to do (we have to do it anyway for processes on remote machines), but a bit annoying.

I would love to have the kind of stitching-together for distributed systems, so I don't think it's a burden to have to do it for these local parallel traces.

**Comment by rocallahan** [comment]
Call me a coward but I don't feel comfortable introducing multithreading this way. The existing compression threading was carefully limited from the beginning and is basically zero maintenance. OTOH the Session/Task/etc stuff was never designed to support multithreaded operation, nor have we been diligent about avoiding mutable global state. Furthermore C++ is not a suitable language for this kind of unstructured parallelism. I don't want to have to start running TSAN tests etc. Maybe I'm overreacting but this seems to me to be opening a real can of worms.

**Comment by Keno** [comment]
Ok, fair enough. It is intentionally very limited in that the new thread only gets the new RecordSession, but with a shared address space, these kinds of bugs can certainly happen. I think the best way forward then would be to remove the `CLONE_VM` and `CLONE_FDS` and make it a true fork. I think cleaning up the resources is probably easier than trying to serialize the task across to a new process.

**Comment by rocallahan** [comment]
I also worry that shared address space + fd table but different threadgroup is just weird and could become a problem, e.g. when debugging rr.

**Comment by rocallahan** [comment]
> I think cleaning up the resources is probably easier than trying to serialize the task across to a new process

OK let's do that then.

**Comment by Keno** [comment]
> I also worry that shared address space + fd table but different threadgroup is just weird and could become a problem, e.g. when debugging rr.

Interestingly gdb is actually just fine with it and treats is as just another thread, because ptrace doesn't talk about thread groups much at all. I too was expecting some problems.

> OK let's do that then.

Ok, let me do that.

**Comment by Keno** [comment]
Actually, now that I've thought about it some more - Given that we already have threads running the in the old address space in an unknown state, cleaning those up in a forked address space is likely to be problematic. The only way I can think of to really accomplish that is to thread a custom allocator through everything and then bulk free it. I keep coming back to the solution in this PR as the least problematic one. The ownership of the new process is fairly well defined. It owns the new RecordSession and everything that references, but nothing else. It shouldn't be possible to introduce a data race (assuming the allocator is ok of course). Let me ponder it some more though and see if I can come up with an easy alternative solution.

**Comment by rocallahan** [comment]
> The ownership of the new process is fairly well defined. It owns the new RecordSession and everything that references, but nothing else.

It does also introduce the requirement that any global state, caching etc, be thread-safe.

Maybe look a bit harder at what's required if we exec after fork?

**Comment by Keno** [comment]
Perhaps, we could go for a middle ground and use a custom slab allocator for everything that the compression threads touch? Then we can kill that allocator all at once, and not worry about what state the threads were in. Trying to preserve enough state across the exec to continue recording just seems like it's always gonna be brittle and will need special attention whenever the state kept by `Task` is changed. It'd like to avoid that if at all possible.

**Comment by Keno** [comment]
Or actually, what if we put the compression threads in their own process and only communicate with them via a well defined, small shared memory buffer interface.

**Comment by rocallahan** [comment]
> Or actually, what if we put the compression threads in their own process and only communicate with them via a well defined, small shared memory buffer interface.

Mmm. One thing I've always wanted to do is have trace compression and writing in its own process so that if you SIGKILL rr we get a clean trace. Maybe this is the time to do that.

**Comment by Keno** [comment]
Completely unrelatedly, but looking over the CompressedWriter class, I'm wondering if we're leaving performance on the table by only issuing one write call to the kernel at a time. Or maybe the
compression throughput is just completely trumping that. If I had nothing else to do, I'd do some performance investigations around that. Perhaps one interesting thing to do would be to add a field to the traces that counts how much time was spent waiting for the compression threads to drain the buffer. That way we could see some statistics across all the logs we're collecting.

**Comment by rocallahan** [comment]
I haven't ever seen trace write performance being a problem since we implemented multithreaded compression a very long time ago. I would not recommend anyone investigating that unless someone stumbles over evidence it's a problem.

**Comment by Keno** [comment]
Good to know, thanks.

**Comment by Keno** [comment]
> Maybe this is the time to do that.

Alright, how do you want to proceed on this? If it's just a matter of moving CompressedWriter to a separate process, I can do that and I do think it would solve the present conundrum in this PR. Did you imagine something more extensive than that? TBH, I'm a bit burnt out on this particular change (this is probably like the 5th time I've tried to get this to work ;) ), so if there's much more to be done, I might have to leave it for a few days.

**Comment by rocallahan** [comment]
> If it's just a matter of moving CompressedWriter to a separate process, I can do that and I do think it would solve the present conundrum in this PR.

That's fine, let's do that.

> TBH, I'm a bit burnt out on this particular change (this is probably like the 5th time I've tried to get this to work ;) ), so if there's much more to be done, I might have to leave it for a few days.

I understand. I'm trying to navigate the tradeoff between expedience and maintainability and we won't always get it right so I apologize in advance if we get it wrong.

**Comment by Keno** [comment]
Replaced by #2485

**Pull request closed without merging**
