### PR TITLE
intelXeon support added for new laptops

### PR DESCRIPTION
**Pull request by am06**

### CODE REVIEW

**Comment by rocallahan** [comment]
"Xeon" isn't the right name here, it's a generic term that covers lots of different kinds of CPUs. Paste `grep model /proc/cpuinfo`?

**Comment by khuey** [comment]
I believe this is another Ice Lake microarchitecture CPU so there's no need to add a new `IntelBlah` variant at all, just a new case in the switch statement.

**Comment by am06** [comment]
grep model /proc/cpuinfo 
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz
model		: 165
model name	: Intel(R) Xeon(R) W-10885M CPU @ 2.40GHz

**Comment by rocallahan** [comment]
It's Comet Lake. So just add `0xa0650` to the `return IntelCometLake;` case.

**Pull request closed without merging**
