### PR TITLE
Disable ReturnAddressList on aarch64 

### PR DESCRIPTION
**Pull request by Keno**
Plus a small bugfix

### CODE REVIEW

**Comment by rocallahan** [comment]
Do we actually need to use `ReturnAddressList` for ARM? IIRC we are counting all taken branches on ARM. That *should* mean it is impossible to revisit the same PC without an intervening tick ... right? In which case, ticks + PC is unique and we shouldn't need `ReturnAddressList`.

**Comment by Keno** [comment]
Fair point, I believe you are likely correct. Modulo weird things like signals occurring and jumping around perhaps. I would be game to try without it and see if we run into any trouble and if so if we can address it without introducing this.

**Comment by rocallahan** [comment]
Signals trigger new events so that shouldn't be a problem. Yes, I think we should at least try not supporting `ReturnAddressList` (or just stubbing it out).

**Comment by Keno** [comment]
(I've updated this to not record any return addresses on aarch64 - we'll see how it goes).

**Pull request merged**
