### PR TITLE
add support for setuid, setuid32 syscalls

### PR DESCRIPTION
**Pull request by pspacek**
DNS server BIND is not going to work without this.

### CODE REVIEW

**Comment by pspacek** [comment]
Oh, wait! rr hangs when traced process forks after setuid(). Wild guess is that something bad happens when traced child is running under different UID than UID of owner of /tmp/rr-tracee-fd-transfer-* socket.

It seems that the problem goes away if I forcibly call umask(000) in rr's main() function, which is of course just a hacky workaround. For now I'm lost in rr's internals and do not know where to look.

Would it be okay to create the socket generally world-writeable? Or should I hook setuid() emulation and do something like setfacl to grant access to the sockets to the new user? That could be fragile, because it depens on POSIX ACL support on the filesystem and so on.

**Comment by rocallahan** [comment]
Mmm, this is a tricky one! :-) Until now rr has assumed the tracees are running with the same UID as rr, so I'm not sure how many things need to fixed here.

`AutoRemoteSyscalls::retrieve_fd_arch` definitely needs to be fixed. Just making the socket world-writeable potentially introduces a security hole, because arbitrary users can then interfere with rr in ways that I really don't want to try to reason about. I can think of two ways to fix this:
* Make it world-writeable and use `SO_PEERCRED` to verify that the pid of the client is the tracee pid.
* Make it world-writeable and generate a random N-byte key in rr, send that key as the bytes of the child message, and verify that we received the key in rr.
Either way, it would be good to have a test to ensure the security measures work. Maybe we'd need an option to rr that adds a delay after creating the socket to give a test attacker a chance to connect. I think I prefer the `SO_PEERCRED` approach.

**Comment by rocallahan** [comment]
As I noted in the other bug, we can write tests that would normally need root privileges by changing to a new UID namespace. Unfortunately in this case that wouldn't really help because the tracee would always seem to keep the same UID from rr's perspective.

**Comment by rocallahan** [comment]
Merged. Thanks! The failure when forking after a setuid should be put into a separate issue.

**Pull request closed without merging**
