### PR TITLE
PAGE_SIZE -> sysconf(_SC_PAGESIZE)

### PR DESCRIPTION
**Pull request by Keno**
For architectures where PAGE_SIZE is variable and thus not defined
as a constant.

Left over from experimenting with rr on other architectures (on hold
for now), but figured I'd put up the mechanical bits to save myself
or others time next time around.

### CODE REVIEW

**Comment by rocallahan** [comment]
Merged, thanks!

I'm kinda curious as to what these architectures are, why `PAGE_SIZE` can't be a compile-time constant in them, and whether rr itself can be made to work with that limitation...

**Comment by Keno** [comment]
> I'm kinda curious as to what these architectures are,

This was PPC64

> why PAGE_SIZE can't be a compile-time constant in them,

The page size can be changed in hardware. As far as I know, on Linux this is a kernel-compile-time constant, though the userspace ABI is the same. On other OSs, the different processes may have different page sizes I believe.

> and whether rr itself can be made to work with that limitation...

The system I have had 4k pages, so I didn't notice any problems related to that (other than at compile time). I fairly confident that rr could be made to work on this machine, but it would require some changes to perf_events, and I wasn't at liberty to modify the kernel.

**Comment by Keno** [comment]
> The system I have had 4k pages,

I was wrong about that BTW. The system's page size is 64k.

**Comment by grooverdan** [comment]
aarch64 also seemed configurable at once stage - https://github.com/jemalloc/jemalloc/issues/467

**Pull request closed without merging**
