### PR TITLE
Add a history command

### PR DESCRIPTION
**Pull request by bgirard**
I left out the 'history' or 'info history' command. This is because the command would require a 'rr-where' command to be executed after each gdb.stop and could hurt interactivity performance. I bet it's not that much but for now I'd rather get this landed and we can fork a different discussion on how costly that command is, if we have a faster alternative and if the delay is acceptable.

### CODE REVIEW

**Comment by bgirard** [comment]
The first changeset should hopefully not be contentions.

The second changeset requires post_cmds which is not as clear. If you don't like it we could just leave it out. It does make using the command much nicer however. We could perhaps find an alternative.

I haven't been able to test this with a real session so once we merge it it would be nice to get feedback and see how reliable/useful the command is.

**Comment by bgirard** [comment]
Context in Issue #1624

**Comment by rocallahan** [comment]
> The second changeset requires post_cmds which is not as clear. If you don't like it we could just leave it out. It does make using the command much nicer however. We could perhaps find an alternative.

These look OK to me. However, couldn't the same effect be achieved with gdb commands like `define hookpost-back` and `define hookpost-forward` in the rr standard gdb prelude? If it was done that way, then users could override those hooks to make them do nothing or do something else, which would be more flexible.

**Comment by rocallahan** [comment]
I merged the first commit.

**Comment by bgirard** [comment]
Ohh great. I wasn't familiar with that and it seems must better. I'll try to re-implement the second changeset using it.

**Pull request closed without merging**
