### PR TITLE
Add PmuConfig for Intel Denvertron

### PR DESCRIPTION
**Pull request by namibj**
This patch was suggested/requested in mozilla/rr#2343

It still fails tests though. See the issue linked above for details.

### CODE REVIEW

**Comment by namibj** [comment]
> Looks fine, but just one problem: It's "Denverton", not "Denvertron".

You don't want to change it directly to Goldmont, while we're at it?
Because the successor of Silvermont is Goldmont, not Denverton.

**Comment by rocallahan** [comment]
OK, good point. Make it Goldmont.

**Comment by rocallahan** [comment]
Can you squash these and force-push the result?

**Comment by rocallahan** [comment]
Never mind, I squashed it myself. https://github.com/mozilla/rr/commit/62b51fd9e69a809c88736127a9565fb071916d67
Thanks!!!

**Pull request closed without merging**
