### PR TITLE
Add syscall buffering for statx/rmdir

### PR DESCRIPTION
**Pull request by Keno**
This makes one of our test cases about 25x faster. It's still not
great - about 3.5x overhead total, but acceptable for the moment.
It looks to me like the remaining overhead is essentially all due
to context switches for syscallbuf flushing.

### CODE REVIEW

**Comment by rocallahan** [comment]
> all due to context switches for syscallbuf flushing.

You could test that by increasing the syscallbuf size.

**Comment by Keno** [comment]
> You could test that by increasing the syscallbuf size.

Yep, in the process of doing that right now ;) - just to see what happens.

**Comment by Keno** [comment]
> Yep, in the process of doing that right now ;) - just to see what happens.

Hmm, that just segfaulted inside the syscallbuf - let me investigate.

**Comment by Keno** [comment]
Alright, I've done some performance experiments here. Bumping the syscallbuf size does not seem to help. However, increasing the default time slice by 100x made quite a noticeable impact bringing down the overall slowdown from recording with rr to just about 2x. In this particular test case, there's only one active thread, all the other threads are blocked on workqueues. Perhaps we can put some smarts in the scheduler to not arm the timeslice or desched signals if there is only one runnable thread. Of course we'd have to rearchitect it a bit to make sure we get woken up if one of the other threads does unexpectedly become runnable, but I think doing something like that could have significant performance benefits.

**Comment by rocallahan** [comment]
That is a bit surprising. What if we just increase the default time slice by 5x? I guess that would reduce the overhead from 3.5x to about 2.3x?

**Comment by rocallahan** [comment]
> make sure we get woken up if one of the other threads does unexpectedly become runnable

That sounds kind of hard.

**Comment by Keno** [comment]
> What if we just increase the default time slice by 5x?

Roughly the same effect as 100x, maybe slightly slower - these measurements are a bit noisy.

**Comment by rocallahan** [comment]
I feel pretty comfortable taking a patch that increases the default time slice by 5x.

**Pull request merged**
